# Generated by Django 6.0.5 on 2026-05-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipamento",
            name="data_devo",
            field=models.DateField(blank=True, null=True),
        ),
    ]
