# Generated by Django 6.0.5 on 2026-05-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0002_equipamento_data_devo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipamento",
            name="ativo",
        ),
        migrations.AddField(
            model_name="equipamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("emprestado", "Emprestado"),
                    ("fornecido", "Fornecido"),
                    ("devolvido", "Devolvido"),
                    ("danificado", "Danificado"),
                    ("perdido", "Perdido"),
                ],
                default="fornecido",
                max_length=20,
            ),
        ),
    ]
